// flow-typed signature: bfce1e0f87f3a8e2c7c0562b9077d6d0
// flow-typed version: <<STUB>>/@types/axios_v^0.14.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/axios' {
  declare module.exports: any;
}
