// flow-typed signature: 32624552a7515eaca41e58f6b042f1fd
// flow-typed version: <<STUB>>/@types/chalk_v^2.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chalk' {
  declare module.exports: any;
}
