// flow-typed signature: d425710fcb8a417206b53d0d1eea2a17
// flow-typed version: <<STUB>>/@types/compression_v^0.0.34/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/compression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/compression' {
  declare module.exports: any;
}
