// flow-typed signature: 1ada604253f76251f8fdbbb58596fa64
// flow-typed version: <<STUB>>/@types/enzyme_v^3.1.8/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/enzyme' {
  declare module.exports: any;
}
