// flow-typed signature: 8c8278274e4f7ce34a91ee9e8ca5b1d8
// flow-typed version: <<STUB>>/@types/express_v^4.11.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express' {
  declare module.exports: any;
}
