// flow-typed signature: 0a9c8bd35d5606e8c905c458fff7bd1e
// flow-typed version: <<STUB>>/@types/jquery_v^3.3.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jquery' {
  declare module.exports: any;
}
