// flow-typed signature: 9bf8e2e4754f5aad69bb322afebc2b8a
// flow-typed version: <<STUB>>/@types/prop-types_v^15.5.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/prop-types' {
  declare module.exports: any;
}
