// flow-typed signature: 3521a0698ae58116f15f176595c9d66c
// flow-typed version: <<STUB>>/@types/react-bootstrap_v^0.32.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-bootstrap' {
  declare module.exports: any;
}
