// flow-typed signature: 5969724c27e7819c74b1daff90a8febf
// flow-typed version: <<STUB>>/@types/react-router-redux_v^5.0.11/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router-redux' {
  declare module.exports: any;
}
