// flow-typed signature: b0260505b8f26baeaafaa3e93d5c09f9
// flow-typed version: <<STUB>>/@types/react-motion_v^0.0.24/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-motion' {
  declare module.exports: any;
}
