// flow-typed signature: 5ae61140984b5030b763a0f1d10ce2bf
// flow-typed version: <<STUB>>/@types/react-router-dom_v^4.2.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router-dom' {
  declare module.exports: any;
}
