// flow-typed signature: 1892d35ff115e88d49394007974831d2
// flow-typed version: <<STUB>>/@types/react-router_v^4.0.21/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router' {
  declare module.exports: any;
}
