// flow-typed signature: aa01f3fa48e0e02bbf432c928469b270
// flow-typed version: <<STUB>>/@types/react-dom_v^16.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
