// flow-typed signature: 46f74333f344669aef37bd8de47554a3
// flow-typed version: <<STUB>>/@types/redux-devtools-extension_v^2.13.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-devtools-extension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-devtools-extension' {
  declare module.exports: any;
}
