// flow-typed signature: f63b3f61b888d497947b5a3dc112647d
// flow-typed version: <<STUB>>/@types/serialize-javascript_v^1.3.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/serialize-javascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/serialize-javascript' {
  declare module.exports: any;
}
