// flow-typed signature: a02f3c3c904eaf46e92e828667fe2547
// flow-typed version: <<STUB>>/@types/webpack_v^3.0.13/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack' {
  declare module.exports: any;
}
