// flow-typed signature: 263bec3db41dbcb6a12da969acddad98
// flow-typed version: <<STUB>>/animate.css_v^3.5.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animate.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animate.css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'animate.css/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'animate.css/gulpfile.js' {
  declare module.exports: $Exports<'animate.css/gulpfile'>;
}
