// flow-typed signature: 57a5f7459c437894095880ac9ec150cc
// flow-typed version: <<STUB>>/apollo-link-context_v^1.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-context/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-context/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-context/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-context/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-context/lib/bundle.umd'>;
}
declare module 'apollo-link-context/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-context/lib/index'>;
}
declare module 'apollo-link-context/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-context/rollup.config'>;
}
