// flow-typed signature: 5ef1ab836451dd26a03aab7b16df3b90
// flow-typed version: <<STUB>>/apollo-link-http_v^1.3.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-http/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-http/lib/httpLink' {
  declare module.exports: any;
}

declare module 'apollo-link-http/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-http/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-http/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-http/lib/bundle.umd'>;
}
declare module 'apollo-link-http/lib/httpLink.js' {
  declare module.exports: $Exports<'apollo-link-http/lib/httpLink'>;
}
declare module 'apollo-link-http/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-http/lib/index'>;
}
declare module 'apollo-link-http/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-http/rollup.config'>;
}
