// flow-typed signature: d9f32f26e91f2a0a8b15e17cb19200c0
// flow-typed version: <<STUB>>/font-awesome_v^4.7.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
