// flow-typed signature: 711ba64d225437de0b5981059a03193b
// flow-typed version: <<STUB>>/js-base64_v^2.4.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-base64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-base64' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-base64/base64' {
  declare module.exports: any;
}

declare module 'js-base64/base64.min' {
  declare module.exports: any;
}

declare module 'js-base64/old/base64-1.7' {
  declare module.exports: any;
}

declare module 'js-base64/package' {
  declare module.exports: any;
}

declare module 'js-base64/test-moment/dankogai' {
  declare module.exports: any;
}

declare module 'js-base64/test-moment/es5' {
  declare module.exports: any;
}

declare module 'js-base64/test-moment/es6' {
  declare module.exports: any;
}

declare module 'js-base64/test-moment/large' {
  declare module.exports: any;
}

declare module 'js-base64/test-moment/moment' {
  declare module.exports: any;
}

declare module 'js-base64/test-moment/yoshinoya' {
  declare module.exports: any;
}

declare module 'js-base64/test/dankogai' {
  declare module.exports: any;
}

declare module 'js-base64/test/es5' {
  declare module.exports: any;
}

declare module 'js-base64/test/es6' {
  declare module.exports: any;
}

declare module 'js-base64/test/large' {
  declare module.exports: any;
}

declare module 'js-base64/test/yoshinoya' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-base64/base64.js' {
  declare module.exports: $Exports<'js-base64/base64'>;
}
declare module 'js-base64/base64.min.js' {
  declare module.exports: $Exports<'js-base64/base64.min'>;
}
declare module 'js-base64/old/base64-1.7.js' {
  declare module.exports: $Exports<'js-base64/old/base64-1.7'>;
}
declare module 'js-base64/package.js' {
  declare module.exports: $Exports<'js-base64/package'>;
}
declare module 'js-base64/test-moment/dankogai.js' {
  declare module.exports: $Exports<'js-base64/test-moment/dankogai'>;
}
declare module 'js-base64/test-moment/es5.js' {
  declare module.exports: $Exports<'js-base64/test-moment/es5'>;
}
declare module 'js-base64/test-moment/es6.js' {
  declare module.exports: $Exports<'js-base64/test-moment/es6'>;
}
declare module 'js-base64/test-moment/large.js' {
  declare module.exports: $Exports<'js-base64/test-moment/large'>;
}
declare module 'js-base64/test-moment/moment.js' {
  declare module.exports: $Exports<'js-base64/test-moment/moment'>;
}
declare module 'js-base64/test-moment/yoshinoya.js' {
  declare module.exports: $Exports<'js-base64/test-moment/yoshinoya'>;
}
declare module 'js-base64/test/dankogai.js' {
  declare module.exports: $Exports<'js-base64/test/dankogai'>;
}
declare module 'js-base64/test/es5.js' {
  declare module.exports: $Exports<'js-base64/test/es5'>;
}
declare module 'js-base64/test/es6.js' {
  declare module.exports: $Exports<'js-base64/test/es6'>;
}
declare module 'js-base64/test/large.js' {
  declare module.exports: $Exports<'js-base64/test/large'>;
}
declare module 'js-base64/test/yoshinoya.js' {
  declare module.exports: $Exports<'js-base64/test/yoshinoya'>;
}
