// flow-typed signature: 7d698d1c8034dafed5466209198e1121
// flow-typed version: <<STUB>>/precss_v^3.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'precss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'precss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'precss/index.bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'precss/index.bundle.js' {
  declare module.exports: $Exports<'precss/index.bundle'>;
}
declare module 'precss/index' {
  declare module.exports: $Exports<'precss'>;
}
declare module 'precss/index.js' {
  declare module.exports: $Exports<'precss'>;
}
