// flow-typed signature: 2940ad90878a62716eb951bf8d7e1f47
// flow-typed version: <<STUB>>/react-modal_v^0.6.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-modal/dist/react-modal' {
  declare module.exports: any;
}

declare module 'react-modal/dist/react-modal.min' {
  declare module.exports: any;
}

declare module 'react-modal/lib/components/Modal' {
  declare module.exports: any;
}

declare module 'react-modal/lib/components/ModalPortal' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/ariaAppHider' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/defaultStyles' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/focusManager' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/scopeTab' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/tabbable' {
  declare module.exports: any;
}

declare module 'react-modal/lib/index' {
  declare module.exports: any;
}

declare module 'react-modal/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-modal/dist/react-modal.js' {
  declare module.exports: $Exports<'react-modal/dist/react-modal'>;
}
declare module 'react-modal/dist/react-modal.min.js' {
  declare module.exports: $Exports<'react-modal/dist/react-modal.min'>;
}
declare module 'react-modal/lib/components/Modal.js' {
  declare module.exports: $Exports<'react-modal/lib/components/Modal'>;
}
declare module 'react-modal/lib/components/ModalPortal.js' {
  declare module.exports: $Exports<'react-modal/lib/components/ModalPortal'>;
}
declare module 'react-modal/lib/helpers/ariaAppHider.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/ariaAppHider'>;
}
declare module 'react-modal/lib/helpers/defaultStyles.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/defaultStyles'>;
}
declare module 'react-modal/lib/helpers/focusManager.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/focusManager'>;
}
declare module 'react-modal/lib/helpers/scopeTab.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/scopeTab'>;
}
declare module 'react-modal/lib/helpers/tabbable.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/tabbable'>;
}
declare module 'react-modal/lib/index.js' {
  declare module.exports: $Exports<'react-modal/lib/index'>;
}
declare module 'react-modal/webpack.config.js' {
  declare module.exports: $Exports<'react-modal/webpack.config'>;
}
